import * as Joi from 'joi';
// import { User } from '../user-auth/user.model';
export class UserValidator {
  public static schema = Joi.object({
    name: Joi.string().min(3).max(30).required(),
    password: Joi.string().min(6).required(),
    email: Joi.string().email().required(),
    profilePicture: Joi.string().allow(""),
    coverPicture: Joi.string().allow(""),
    followers: Joi.array().items(Joi.string()).default([]),
    followings: Joi.array().items(Joi.string()).default([]),
    isAdmin: Joi.boolean().default(false),
    description: Joi.string().allow(""),
    city: Joi.string().max(50).allow(""),
    from: Joi.string().max(50).allow(""),
    relationship: Joi.number().valid(1, 2, 3).allow(""),
    fcmToken: Joi.string().allow(""),
    googleId: Joi.string().allow(""),
    refreshToken: Joi.string().allow(""),
    isVerified: Joi.boolean().default(false),
    otp: Joi.string().allow(""),
    isTwoFactorEnabled: Joi.boolean().default(false),
    twoFactorMethod: Joi.string().allow(""),
    twoFactorSecret: Joi.string().allow(""),
    socialLinks: Joi.object().pattern(Joi.string(), Joi.string()).default({}),
    isActive: Joi.boolean().default(true),
    lastLogin: Joi.date().allow(""),
    loginAttempts: Joi.number().default(0),
    lockUntil: Joi.date().allow(""),
    language: Joi.string().allow(""),
    timezone: Joi.string().allow(""),
    privacySettings: Joi.object({
      profileVisibility: Joi.string().allow(""),
      messagePrivacy: Joi.string().allow("")
    }).default({}),
    isAccessibilityModeEnabled: Joi.boolean().default(false),
    consentToDataProcessing: Joi.boolean().default(false),
    consentToMarketing: Joi.boolean().default(false),
    customFields: Joi.object().pattern(Joi.string(), Joi.string()).default({}),
    address: Joi.object({
      street: Joi.string().allow(""),
      city: Joi.string().allow(""),
      state: Joi.string().allow(""),
      postalCode: Joi.string().allow(""),
      country: Joi.string().allow("")
    }).default({})
  });
  public static schemaUpdate = Joi.object({
    name: Joi.string().min(3).max(30),
    password: Joi.string().min(6),
    email: Joi.string().email(),
    profilePicture: Joi.string().allow(""),
    coverPicture: Joi.string().allow(""),
    followers: Joi.array().items(Joi.string()),
    followings: Joi.array().items(Joi.string()),
    isAdmin: Joi.boolean(),
    description: Joi.string(),
    city: Joi.string().max(50),
    from: Joi.string().max(50),
    relationship: Joi.number().valid(1, 2, 3),
    fcmToken: Joi.string(),
    googleId: Joi.string().allow(""),
    refreshToken: Joi.string().allow(""),
    isVerified: Joi.boolean(),
    otp: Joi.string(),
    id: Joi.string(),
    isTwoFactorEnabled: Joi.boolean(),
    twoFactorMethod: Joi.string(),
    twoFactorSecret: Joi.string(),
    socialLinks: Joi.object().pattern(Joi.string(), Joi.string()),
    isActive: Joi.boolean(),
    lastLogin: Joi.date(),
    loginAttempts: Joi.number(),
    lockUntil: Joi.date(),
    language: Joi.string(),
    timezone: Joi.string(),
    privacySettings: Joi.object({
      profileVisibility: Joi.string(),
      messagePrivacy: Joi.string(),
    }),
    isAccessibilityModeEnabled: Joi.boolean(),
    consentToDataProcessing: Joi.boolean(),
    consentToMarketing: Joi.boolean(),
    customFields: Joi.object().pattern(Joi.string(), Joi.string()),
    address: Joi.object({
      street: Joi.string(),
      city: Joi.string(),
      state: Joi.string(),
      postalCode: Joi.string(),
      country: Joi.string(),
    }),
  });

}
